### ISSUE TITLE
composer.json not writeable

### ISSUE THREAD

**Issue by jonycp** [pantheon-systems/terminus-composer-plugin#19]
Hello, 

I tried
$ terminus composer ycp-2024-test-site.test -- require 'drupal/tailwindcss:^5.0@alpha'

./composer.json is not writable.

I don't know if it matters, but I did sign in with machine token. 

I started a chat and the rep said he would put in a ticket with a platform engineer.

**Comment by namespacebrian** [comment]
The code is never writable in the test or live environments.  In the dev environment, the site must be put in SFTP mode for the code to be writable.

**Comment by jonycp** [comment]
Wow - sorry, rookie mistake. Thank you!!
